---
# https://github.com/actions/labeler

Build 🔨:
  - "bin/build.sh"
  - "Gemfile"
  - "Gemfile.lock"
  - "_config.yml"
  - "mise.toml"

Code Quality 🔎:
  - ".pre-commit-config.yaml"
  - "lychee.toml"

Source 🗂:
  - "assets/**/*"
  - "index.html"
  - "_data/**/*"
  - "_includes/**/*"
  - "_pages/**/*"
  - "_posts/**/*"
