queue_rules:
  - name: duplicated default from automatic merge on CI success and review
    queue_conditions:
      - base=master
      - author~=proinsias
      - check-success-or-neutral=Deadpendency Check
      - base=master
      - author~=github-actions
      - check-success-or-neutral=Deadpendency Check
    merge_conditions: []
    merge_method: merge
  - name: duplicated default from automatic merge for Dependabot pull requests
    queue_conditions:
      - base=master
      - author~=proinsias
      - check-success-or-neutral=Deadpendency Check
      - base=master
      - author~=dependabot
      - check-success-or-neutral=Deadpendency Check
    merge_conditions: []
    merge_method: merge
  - name: default
    queue_conditions:
      - base=master
      - author~=proinsias
      - check-success-or-neutral=Deadpendency Check
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success-or-neutral=Deadpendency Check
    merge_method: merge

pull_request_rules:
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: automatic merge for Dependabot pull requests + automatic merge for me + automatic merge on CI success and review
    conditions: []
    actions:
      queue:
priority_rules:
  - name: priority for queue `duplicated default from automatic merge on CI success and review`
    conditions:
      - author~=github-actions
    priority: 2500
  - name: priority for queue `duplicated default from automatic merge for Dependabot pull requests`
    conditions:
      - author~=dependabot
    priority: 2250
