---
# This extends the default conf by adjusting some options.

extends: default

rules:
  comments:
    min-spaces-from-content: 1 # Match prettier's formatting style.
  braces:
    max-spaces-inside: 1 # Match prettier's formatting style.
  line-length:
    max: 120
    # level: warning # don't fail if a line is longer.
  truthy:
    allowed-values: ['true', 'false', 'on']
