# Comma-separated list of accepted status codes for valid links.
# default: 100..=103,200..=299
accept = ["100..=103", "200..=299", "403"]

# Exclude URLs and mail addresses from checking (supports regex).
# exclude = ['^https://www.linkedin.com']

# Suggest link replacements for broken links, using a web archive.
suggest = true
